# solving XOR problem using feedforward neural network

In [1]:
import numpy as np
from keras.models import Sequential 
from keras.layers import Dense 

In [2]:
model=Sequential()
model.add(Dense(units=2,activation='relu',input_dim=2))
model.add(Dense(units=1,activation='sigmoid'))

In [3]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
print(model.summary())
print(model.get_weights())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None
[array([[ 0.3666625 , -0.6385685 ],
       [ 0.30479956,  0.81424797]], dtype=float32), array([0., 0.], dtype=float32), array([[-0.10645044],
       [ 0.59742796]], dtype=float32), array([0.], dtype=float32)]


In [4]:
X=np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
print(X)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [5]:
y=np.array([0.,1.,1.,0.])
print(y)

[0. 1. 1. 0.]


In [6]:
model.fit(X,y,epochs=100,batch_size=4)

Epoch 1/100
1/1 [==============================] - 0s 423ms/step - loss: 0.6519 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6517 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6515 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6513 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6511 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6508 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6506 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6504 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6502 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6500 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 0.6352 - accuracy: 0.7500
Epoch 85/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6351 - accuracy: 0.7500
Epoch 86/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6349 - accuracy: 0.7500
Epoch 87/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6347 - accuracy: 0.7500
Epoch 88/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.7500
Epoch 89/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6343 - accuracy: 0.7500
Epoch 90/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6341 - accuracy: 0.7500
Epoch 91/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6339 - accuracy: 0.7500
Epoch 92/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6337 - accuracy: 0.7500
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6336 - accuracy: 0.7500
Epoch 94/100
1/1 [===============

In [7]:
print(model.get_weights())

[array([[ 0.23277819, -0.7311719 ],
       [ 0.3982818 ,  0.7727072 ]], dtype=float32), array([-0.11446516, -0.0415404 ], dtype=float32), array([[-0.2120913 ],
       [ 0.70237935]], dtype=float32), array([-0.06308579], dtype=float32)]


In [8]:
predictions=model.predict(X)
predictions

1/1 [==============================] - 0s 76ms/step


array([[0.48423377],
       [0.5963491 ],
       [0.47796956],
       [0.45694417]], dtype=float32)

In [19]:
def vec2scalar(list_):
    pred=[]
    for i in predictions:
        if i>0.5:
            pred.append(1)
        else:
            pred.append(0)
    return pred

In [20]:
vec2scalar(predictions)

[0, 1, 0, 0]