In [1]:
import tensorflow as tf

# Creating matrices of different shape using constant values with the help of tensorflow library.

In [2]:
X = tf.constant([1,2,3,4,5,6],shape=[3,2])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [3]:
Y = tf.constant([1,2,3,4,5,6],shape=[2,3])
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

# Create a 4*4 square matrix A with constant values from 1 to 16.

In [4]:
Z = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],shape=[4,4])
Z

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])>

Demonstrate matrix multiplication with the help of function of tensorflow library

In [5]:
Z=tf.matmul(X,Y)
Z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [6]:
A = tf.constant([1,2,3,4,5,6],shape=[2,3])
A

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
B = tf.constant([7,8,9,10,11,12],shape=[3,2])
B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [8]:
C=tf.matmul(A,B)
C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

With the help of tensorflow function create matrix using random values.

Note:- Shape,Range1,Range2,Datatype of the argument.

In [9]:
A= tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.int32)
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [4, 4]])>

In [10]:
B= tf.random.uniform([3,3],minval=3,maxval=10,dtype=tf.float32)
B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[9.94434  , 5.020261 , 7.2950416],
       [6.810136 , 9.122917 , 3.7730494],
       [4.284432 , 3.5842047, 3.5325606]], dtype=float32)>

Create a Matrix C using random values of float datatype having shape 3*2

In [11]:
C = tf.random.uniform([3,2],minval=10,maxval=50,dtype=tf.float32)
C

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[40.640007, 39.361526],
       [18.58648 , 11.213632],
       [33.528328, 46.180786]], dtype=float32)>

In [12]:
eig_values,eig_vectors=tf.linalg.eigh(B)

In [13]:
eig_values

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.3764155,  2.780762 , 18.442646 ], dtype=float32)>

In [14]:
eig_vectors

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4011124 , -0.60604703,  0.6868887 ],
       [ 0.06996883,  0.7679345 ,  0.6366956 ],
       [-0.9133528 , -0.20732562,  0.35043237]], dtype=float32)>